network:
  version: 2
  ethernets:
    ### NAT
    enp0s3:
      addresses:
        - 10.0.2.15/24
      routes:
        - to: default
          via: 10.0.2.2
          metric: 100
      nameservers:
        addresses:
          - 10.0.2.2

    ### Host only: host networks.
    enp0s8:
      addresses:
        - 192.168.56.2/24

    ### Bridge: IPv4 private networks.
    enp0s9:
      addresses:
        - 192.168.11.7/24
      routes:
        - to: default
          via: 192.168.11.1
          metric: 102
      nameservers:
        addresses:
          - 192.168.11.1
