[[plugins]]
repo  = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript', 'typescript']
hook_source = '''
  let g:prettier#autoformat = 0
  autocmd BufWritePre *.js,*.json,*.tsx PrettierAsync
'''
